/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import crud.Buku;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class Form_Buku extends javax.swing.JFrame {
    private DefaultTableModel tabMode;
    private ResultSet hasil;
    
    Buku crud = new Buku();
    ButtonGroup bg;

    /**
     * Creates new form Form_Pengguna
     */
    public Form_Buku(){
        initComponents();
        tampilDatabase();
        tampilKategori();
    }
    
    public void tampilDatabase() {
        Object[] baris = {"No Induk Buku", "Judul Buku", "Pengarang", "Penerbit", "Kategori", "Jumlah", "Tersedia", "Keluar", "Tahun", "Klasifikasi", "Lokasi Buku"}; 
        tabMode = new DefaultTableModel(null, baris); 
        tabel_buku.setModel(tabMode);
            try {
               hasil = crud.tampilData();
                while (hasil.next()){
                    String[] data = {
                        hasil.getString("no_induk_buku"),
                        hasil.getString("judul"),
                        hasil.getString("pengarang"),
                        hasil.getString("penerbit"),
                        hasil.getString("nama_kategori"),
                        hasil.getString("jumlah"),
                        hasil.getString("tersedia"),
                        hasil.getString("keluar"),
                        hasil.getString("tahun_terbit"),
                        hasil.getString("no_klasifikasi"),
                        hasil.getString("lokasi_buku")
                    };
                    crud.setDataBuku(data);
                    tabMode.addRow(crud.getDataBuku());
                }
            } catch (Exception e) {
                
            }      
    }
    
    
    public void tampilKategori() {
            try {
               hasil = crud.tampilKategori();
                while (hasil.next()){
                    option_kategori.addItem(hasil.getString(1) + " - " + hasil.getString(2));
                }
            } catch (Exception e) {
                
            }      
    }
    
    public void resetText() { 
        txt_nib.setText(""); 
        txt_judulBuku.setText("");
        txt_pengarang.setText("");
        txt_penerbit.setText("");
        option_kategori.setSelectedItem("-");
        txt_jumlahBuku.setText("0");
        txt_tahunTerbit.setText("");
        txt_tersedia.setText("");
        txt_keluar.setText("");
        txt_noKlasifikasi.setText("");
        txt_lokasiBuku.setText("");
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nib = new javax.swing.JTextField();
        txt_judulBuku = new javax.swing.JTextField();
        txt_pengarang = new javax.swing.JTextField();
        txt_penerbit = new javax.swing.JTextField();
        ubah_buku = new javax.swing.JButton();
        tambah_buku = new javax.swing.JButton();
        hapus_buku = new javax.swing.JButton();
        reset_buku = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_jumlahBuku = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_buku = new javax.swing.JTable();
        keluar_buku = new javax.swing.JButton();
        txt_tahunTerbit = new javax.swing.JTextField();
        txt_noKlasifikasi = new javax.swing.JTextField();
        txt_lokasiBuku = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        option_kategori = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_tersedia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_keluar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("No. Induk Buku");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Judul Buku");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Pengarang");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Penerbit");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_nib.setBackground(new java.awt.Color(255, 255, 255));
        txt_nib.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nib.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_nib.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_nib.setMargin(new java.awt.Insets(0, 3, 0, 3));
        txt_nib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nibActionPerformed(evt);
            }
        });

        txt_judulBuku.setBackground(new java.awt.Color(255, 255, 255));
        txt_judulBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_judulBuku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_judulBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_judulBuku.setMargin(new java.awt.Insets(0, 3, 0, 3));

        txt_pengarang.setBackground(new java.awt.Color(255, 255, 255));
        txt_pengarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_pengarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_pengarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_pengarang.setMargin(new java.awt.Insets(0, 3, 0, 3));

        txt_penerbit.setBackground(new java.awt.Color(255, 255, 255));
        txt_penerbit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_penerbit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_penerbit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_penerbit.setMargin(new java.awt.Insets(0, 3, 0, 3));

        ubah_buku.setText("Ubah");
        ubah_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_bukuActionPerformed(evt);
            }
        });

        tambah_buku.setText("Tambah");
        tambah_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_bukuActionPerformed(evt);
            }
        });

        hapus_buku.setText("Hapus");
        hapus_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_bukuActionPerformed(evt);
            }
        });

        reset_buku.setText("Reset");
        reset_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_bukuActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Tahun Terbit");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_jumlahBuku.setBackground(new java.awt.Color(255, 255, 255));
        txt_jumlahBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_jumlahBuku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_jumlahBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_jumlahBuku.setMargin(new java.awt.Insets(0, 3, 0, 3));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Jumlah Buku");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_cari.setBackground(new java.awt.Color(255, 255, 255));
        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cari.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_cari.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_cari.setMargin(new java.awt.Insets(0, 3, 0, 3));
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        tabel_buku.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tabel_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Induk Buku", "Judul Buku", "Pengarang", "Penerbit", "Kategori", "Jumlah", "Tersedia", "Keluar", "Tahun", "Klasifikasi", "Lokasi Buku"
            }
        ));
        tabel_buku.setRowHeight(17);
        tabel_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_bukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_buku);

        keluar_buku.setText("Keluar");
        keluar_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar_bukuActionPerformed(evt);
            }
        });

        txt_tahunTerbit.setBackground(new java.awt.Color(255, 255, 255));
        txt_tahunTerbit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_tahunTerbit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_tahunTerbit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_tahunTerbit.setMargin(new java.awt.Insets(0, 3, 0, 3));

        txt_noKlasifikasi.setBackground(new java.awt.Color(255, 255, 255));
        txt_noKlasifikasi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_noKlasifikasi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_noKlasifikasi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_noKlasifikasi.setMargin(new java.awt.Insets(0, 3, 0, 3));

        txt_lokasiBuku.setBackground(new java.awt.Color(255, 255, 255));
        txt_lokasiBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_lokasiBuku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_lokasiBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_lokasiBuku.setMargin(new java.awt.Insets(0, 3, 0, 3));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("No. Klasifikasi");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Lokasi Buku");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        option_kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        option_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option_kategoriActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Kategori");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Keluar");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_tersedia.setBackground(new java.awt.Color(255, 255, 255));
        txt_tersedia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_tersedia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_tersedia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_tersedia.setMargin(new java.awt.Insets(0, 3, 0, 3));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Tersedia");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_keluar.setBackground(new java.awt.Color(255, 255, 255));
        txt_keluar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_keluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_keluar.setMargin(new java.awt.Insets(0, 3, 0, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(keluar_buku, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(39, 39, 39)
                                .addComponent(txt_nib, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(67, 67, 67))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(84, 84, 84)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(option_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_judulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_tahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_jumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_tersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_noKlasifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_lokasiBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambah_buku)
                        .addGap(18, 18, 18)
                        .addComponent(ubah_buku)
                        .addGap(18, 18, 18)
                        .addComponent(hapus_buku)
                        .addGap(18, 18, 18)
                        .addComponent(reset_buku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_nib, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txt_jumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_judulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(txt_tahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txt_tersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txt_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_noKlasifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_lokasiBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(option_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubah_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(keluar_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ubah_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_bukuActionPerformed
        // TODO add your handling code here:
        if (txt_nib.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nomor Induk Buku belum diisi !"); txt_nib.requestFocus();
        } else if (txt_judulBuku.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Judul Buku belum diisi !"); txt_judulBuku.requestFocus();
        } else if (txt_pengarang.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Pengarang belum diisi!"); txt_pengarang.requestFocus();
        } else if (txt_penerbit.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Penerbit belum diisi!"); txt_penerbit.requestFocus();
        }else if (option_kategori.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, kategori belum diisi!"); option_kategori.requestFocus();
        }else if (txt_jumlahBuku.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, jumlahBuku belum diisi!"); txt_jumlahBuku.requestFocus();
        }else if (txt_tahunTerbit.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, tahunTerbit belum diisi!"); txt_tahunTerbit.requestFocus();
        }else if (txt_tersedia.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, tersedia belum diisi!"); txt_tersedia.requestFocus();
        }else if (txt_keluar.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, keluar belum diisi!"); txt_keluar.requestFocus();
        }else if (txt_noKlasifikasi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, noKlasifikasi belum diisi!"); txt_noKlasifikasi.requestFocus();
        }else if (txt_lokasiBuku.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, lokasiBuku belum diisi!"); txt_lokasiBuku.requestFocus();
        } else {
            try {
                String kategori = option_kategori.getSelectedItem().toString();
                String[] kata = kategori.split("-");
                String[] setData = {
                    txt_judulBuku.getText(),
                    txt_pengarang.getText(),
                    txt_penerbit.getText(),
                    kata[0],
                    txt_jumlahBuku.getText(),
                    txt_tersedia.getText(),
                    txt_keluar.getText(),
                    txt_tahunTerbit.getText(),
                    txt_noKlasifikasi.getText(),
                    txt_lokasiBuku.getText(),
                    txt_nib.getText(),

                };
                crud.setDataBuku(setData);
                crud.ubahData(crud.getDataBuku());
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampilDatabase();
            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, "Data gagal diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_ubah_bukuActionPerformed

    private void tambah_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_bukuActionPerformed
        // TODO add your handling code here:
        if (txt_nib.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nomor Induk Buku belum diisi !"); txt_nib.requestFocus();
        } else if (txt_judulBuku.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Judul Buku belum diisi !"); txt_judulBuku.requestFocus();
        } else if (txt_pengarang.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Pengarang belum diisi!"); txt_pengarang.requestFocus();
        } else if (txt_penerbit.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Penerbit belum diisi!"); txt_penerbit.requestFocus();
        }else if (option_kategori.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, kategori belum diisi!"); option_kategori.requestFocus();
        }else if (txt_jumlahBuku.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, jumlahBuku belum diisi!"); txt_jumlahBuku.requestFocus();
        }else if (txt_tahunTerbit.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, tahunTerbit belum diisi!"); txt_tahunTerbit.requestFocus();
        }else if (txt_tersedia.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, tersedia belum diisi!"); txt_tersedia.requestFocus();
        }else if (txt_keluar.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, keluar belum diisi!"); txt_keluar.requestFocus();
        }else if (txt_noKlasifikasi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, noKlasifikasi belum diisi!"); txt_noKlasifikasi.requestFocus();
        }else if (txt_lokasiBuku.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, lokasiBuku belum diisi!"); txt_lokasiBuku.requestFocus();
        } else {
            try {
                String kategori = option_kategori.getSelectedItem().toString();
                String[] kata = kategori.split("-");
                String[] setData = {
                    txt_nib.getText(),
                    txt_judulBuku.getText(),
                    txt_pengarang.getText(),
                    txt_penerbit.getText(),
                    kata[0],
                    txt_jumlahBuku.getText(),
                    txt_tersedia.getText(),
                    txt_keluar.getText(),
                    txt_tahunTerbit.getText(),
                    txt_noKlasifikasi.getText(),
                    txt_lokasiBuku.getText(),
                };
                crud.setDataBuku(setData);
                crud.simpanData(crud.getDataBuku());
                JOptionPane.showMessageDialog(null, "Data Berhasil Tersimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampilDatabase(); resetText();
            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, "Data Gagal Tersimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_tambah_bukuActionPerformed

    private void hapus_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_bukuActionPerformed
        if (txt_nib.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nomor Induk Buku belum diisi !"); txt_nib.requestFocus();
        } 
        else {
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ?", "Warning", 2) == JOptionPane.YES_OPTION) {
            String nib = ""; 
            try {
                String[] data = {txt_nib.getText()};
                crud.setDataBuku(data);
                crud.hapusData(crud.getDataBuku()[0]); 
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus",
                "Informasi", JOptionPane.INFORMATION_MESSAGE); tampilDatabase();
                resetText();
            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, "Data gagal dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        }
    }//GEN-LAST:event_hapus_bukuActionPerformed

    private void reset_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_bukuActionPerformed
        // TODO add your handling code here:
        resetText();
    }//GEN-LAST:event_reset_bukuActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
        Object[] baris = {"No. Induk Buku", "Nama Buku", "Pengarang", "Penerbit", "Kategori", "Jumlah", "Tersedia", "Keluar", "Tahun", "Klasifikasi", "Lokasi Buku",};
        tabMode = new DefaultTableModel(null, baris); tabel_buku.setModel(tabMode);
        try {
            hasil = crud.cariData(txt_cari.getText()); 
            while (hasil.next()) {
                String[] data = {
                        hasil.getString("no_induk_buku"),
                        hasil.getString("nama_buku"),
                        hasil.getString("pengarang"),
                        hasil.getString("penerbit"),
                        hasil.getString("kategori_id"),
                        hasil.getString("jumlah"),
                        hasil.getString("tersedia"),
                        hasil.getString("keluar"),
                        hasil.getString("tahun_terbit"),
                        hasil.getString("no_klasifikasi"),
                        hasil.getString("lokasi_buku")
                    };
                crud.setDataBuku(data);
                tabMode.addRow(crud.getDataBuku());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txt_cariActionPerformed

    private void tabel_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_bukuMouseClicked
         // TODO add your handling code here:
        txt_nib.setText(tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 0).toString());
        txt_judulBuku.setText(tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 1).toString());
        txt_pengarang.setText(tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 2).toString());
        txt_penerbit.setText(tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 3).toString());
        String nama_kategori = tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 4).toString();
        try {
            hasil = crud.getIdKategori(nama_kategori); 
            while (hasil.next()) {
                String[] data = {
                    hasil.getString("id"),
                };
                option_kategori.setSelectedItem(data[0] +" - " + nama_kategori);
            }
        } catch (Exception e) {
        }
        txt_jumlahBuku.setText(tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 5).toString());
        txt_tahunTerbit.setText(tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 8).toString());
        txt_tersedia.setText(tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 6).toString());
        txt_keluar.setText(tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 7).toString());
        txt_noKlasifikasi.setText(tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 9).toString());
        txt_lokasiBuku.setText(tabel_buku.getValueAt(tabel_buku.getSelectedRow(), 10).toString());
        
    }//GEN-LAST:event_tabel_bukuMouseClicked

    private void txt_nibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nibActionPerformed

    private void keluar_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluar_bukuActionPerformed

    private void option_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option_kategoriActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        Object[] baris = {"No Induk Buku", "Judul Buku", "Pengarang", "Penerbit", "Kategori", "Jumlah", "Tersedia", "Keluar", "Tahun", "Klasifikasi", "Lokasi Buku"}; 
        tabMode = new DefaultTableModel(null, baris); 
        tabel_buku.setModel(tabMode);
            try {
               hasil = crud.cariData(txt_cari.getText());
                while (hasil.next()){
                    String[] data = {
                        hasil.getString("no_induk_buku"),
                        hasil.getString("judul"),
                        hasil.getString("pengarang"),
                        hasil.getString("penerbit"),
                        hasil.getString("nama_kategori"),
                        hasil.getString("jumlah"),
                        hasil.getString("tersedia"),
                        hasil.getString("keluar"),
                        hasil.getString("tahun_terbit"),
                        hasil.getString("no_klasifikasi"),
                        hasil.getString("lokasi_buku")
                    };
                    crud.setDataBuku(data);
                    tabMode.addRow(crud.getDataBuku());
                }
            } catch (Exception e) {
                
            }      
    }//GEN-LAST:event_txt_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Form_Buku().setVisible(true);
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus_buku;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keluar_buku;
    private javax.swing.JComboBox option_kategori;
    private javax.swing.JButton reset_buku;
    private javax.swing.JTable tabel_buku;
    private javax.swing.JButton tambah_buku;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_judulBuku;
    private javax.swing.JTextField txt_jumlahBuku;
    private javax.swing.JTextField txt_keluar;
    private javax.swing.JTextField txt_lokasiBuku;
    private javax.swing.JTextField txt_nib;
    private javax.swing.JTextField txt_noKlasifikasi;
    private javax.swing.JTextField txt_penerbit;
    private javax.swing.JTextField txt_pengarang;
    private javax.swing.JTextField txt_tahunTerbit;
    private javax.swing.JTextField txt_tersedia;
    private javax.swing.JButton ubah_buku;
    // End of variables declaration//GEN-END:variables
}
