/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import javax.swing.JFrame;

/**
 *
 * @author hadif
 */
public class FormDashboard extends javax.swing.JFrame {

    private FormLogin formlogin;
    
    
    public FormDashboard() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuKategori = new javax.swing.JMenuItem();
        menuBuku = new javax.swing.JMenuItem();
        menuAnggota = new javax.swing.JMenuItem();
        menuPengguna = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuTransaksiPeminjaman = new javax.swing.JMenuItem();
        menuTransaksiPengembalian = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuLaporanPeminjaman = new javax.swing.JMenuItem();
        menuLaporanPengembalian = new javax.swing.JMenuItem();
        menuPengaturan = new javax.swing.JMenu();
        menuDenda = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenu();
        subMenuKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nunito", 1, 48)); // NOI18N
        jLabel1.setText("APLIKASI PERPUSTAKAAN");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/politani-samarinda.png"))); // NOI18N

        jMenu1.setText("Master");

        menuKategori.setText("Kategori");
        menuKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKategoriActionPerformed(evt);
            }
        });
        jMenu1.add(menuKategori);

        menuBuku.setText("Buku");
        menuBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBukuActionPerformed(evt);
            }
        });
        jMenu1.add(menuBuku);

        menuAnggota.setText("Anggota");
        menuAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnggotaActionPerformed(evt);
            }
        });
        jMenu1.add(menuAnggota);

        menuPengguna.setText("Pengguna");
        menuPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenggunaActionPerformed(evt);
            }
        });
        jMenu1.add(menuPengguna);

        menuBar.add(jMenu1);

        jMenu2.setText("Transaksi");

        menuTransaksiPeminjaman.setText("Peminjaman");
        menuTransaksiPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiPeminjamanActionPerformed(evt);
            }
        });
        jMenu2.add(menuTransaksiPeminjaman);

        menuTransaksiPengembalian.setText("Pengembalian");
        menuTransaksiPengembalian.setToolTipText("");
        menuTransaksiPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiPengembalianActionPerformed(evt);
            }
        });
        jMenu2.add(menuTransaksiPengembalian);

        menuBar.add(jMenu2);

        jMenu3.setText("Laporan");

        menuLaporanPeminjaman.setText("Peminjaman");
        menuLaporanPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanPeminjamanActionPerformed(evt);
            }
        });
        jMenu3.add(menuLaporanPeminjaman);

        menuLaporanPengembalian.setText("Pengembalian");
        menuLaporanPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanPengembalianActionPerformed(evt);
            }
        });
        jMenu3.add(menuLaporanPengembalian);

        menuBar.add(jMenu3);

        menuPengaturan.setText("Pengaturan");

        menuDenda.setText("Denda");
        menuDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDendaActionPerformed(evt);
            }
        });
        menuPengaturan.add(menuDenda);

        menuBar.add(menuPengaturan);

        menuKeluar.setText("Keluar");

        subMenuKeluar.setText("Keluar");
        subMenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuKeluarActionPerformed(evt);
            }
        });
        menuKeluar.add(subMenuKeluar);

        menuBar.add(menuKeluar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel2)))
                .addContainerGap(920, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(528, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKategoriActionPerformed
        FormKategori frameform = new FormKategori();
        frameform.setVisible(true);
    }//GEN-LAST:event_menuKategoriActionPerformed

    private void menuAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnggotaActionPerformed
        Form_Anggota frameform = new Form_Anggota();
        frameform.setVisible(true);
    }//GEN-LAST:event_menuAnggotaActionPerformed

    private void menuTransaksiPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiPeminjamanActionPerformed
        TransaksiDataPeminjaman frameform = new TransaksiDataPeminjaman();
        frameform.setVisible(true);
    }//GEN-LAST:event_menuTransaksiPeminjamanActionPerformed

    private void menuPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenggunaActionPerformed
        Form_Pengguna frameform = new Form_Pengguna();
        frameform.setVisible(true);
    }//GEN-LAST:event_menuPenggunaActionPerformed

    private void menuBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBukuActionPerformed
        Form_Buku frameform = new Form_Buku();
        frameform.setVisible(true);
    }//GEN-LAST:event_menuBukuActionPerformed

    private void menuTransaksiPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiPengembalianActionPerformed
        TransaksiDataPengembalian frameform = new TransaksiDataPengembalian();
        frameform.setVisible(true);
    }//GEN-LAST:event_menuTransaksiPengembalianActionPerformed

    private void menuLaporanPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanPeminjamanActionPerformed
        Form_LaporanPeminjaman1 frameform = new Form_LaporanPeminjaman1();
        frameform.setVisible(true);
    }//GEN-LAST:event_menuLaporanPeminjamanActionPerformed

    private void menuLaporanPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanPengembalianActionPerformed
        LaporanPengembalian frameform = new LaporanPengembalian();
        frameform.setVisible(true);
    }//GEN-LAST:event_menuLaporanPengembalianActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        formlogin = new FormLogin();
        formlogin.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void subMenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_subMenuKeluarActionPerformed

    private void menuDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDendaActionPerformed
        data_denda frameform = new data_denda();
        frameform.setVisible(true);
    }//GEN-LAST:event_menuDendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem menuAnggota;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBuku;
    private javax.swing.JMenuItem menuDenda;
    private javax.swing.JMenuItem menuKategori;
    private javax.swing.JMenu menuKeluar;
    private javax.swing.JMenuItem menuLaporanPeminjaman;
    private javax.swing.JMenuItem menuLaporanPengembalian;
    private javax.swing.JMenu menuPengaturan;
    private javax.swing.JMenuItem menuPengguna;
    private javax.swing.JMenuItem menuTransaksiPeminjaman;
    private javax.swing.JMenuItem menuTransaksiPengembalian;
    private javax.swing.JMenuItem subMenuKeluar;
    // End of variables declaration//GEN-END:variables
}
